---

###Research 
&nbsp;

My research involves visual aesthetics and colour preference, focusing on how different colours and visual textures can 

elicit an emotional response. Currently, I am investigating material perception of liquids and whether liquids with 

different colours and simulated viscosities elicit an emotional response and how this is affected through aesthetic 

judgements.

&nbsp;

I want to look further into psychological research in the contemporary art field, that is, how different factors affect 

visual aesthetic judgements such as colour preference and emotions. I am fascinated by this field of research as I paint and 

work with art objects and materials myself, and from a psychological perspective I am interested in thoroughly examining how 

the two factors connect. 

&nbsp; 

###Concept of my work: Oozing Liquids I & II

<iframe width="560" height="315" src="https://www.youtube.com/embed/M5xnAdVPbgQ" frameborder="0" gesture="media" allowfullscreenfloat></iframe>
</iframe><iframe width="560" height="315" src="https://www.youtube.com/embed/mE9VpirfhGk" frameborder="0" gesture="media" allowfullscreenfloat></iframe>

&nbsp; 

###Research Experience

2017 

#####Glasgow Caledonian University 

Volunteer Research Assistant -Institute of Applied Health Research, Public Health Research Group, Glasgow Caledonian University, Psychology Department

• Undertaking Qualitative research

• Constructing two research projects in order to fulfill a publication and currently concentrating on conducting literature    reviews

• Participated in a focus group being a silent observer and took notes regarding observation of group thoughts

• Learned how to conduct BCT (Behavioural Change Techniques), gaining an understanding of BCW (Behaviour Change Wheel)

• Providing external opinion on processes, products, and recommendations 

• Providing feedback on participant interviews, attending research seminars and conferences 

• Conducting thematic analysis 

• Gaining an understanding of the use of NVIvo® 

• Undertaking training in Endnote® 

&nbsp;

###Publications 

2017

#####Glasgow Caledonian University 

Assisted in a research project for Applied Health Research, Public Health Research Group in the Department of Psychology. I was acknowledged in this research project.  

•	 King, C., Currie, K., Dickson, A., Smith, M., Smith, F., & Flowers, P. (2017). Developing interventions to reduce AMR associated with companion animals: A multi-method examination of the existing evidence, UK-expert opinion and the perspectives of the pet-owning public, and companion animal vets. Glasgow, Glasgow Caledonian University (Report submitted to Health Protection Scotland).


 